# generated by clj2nix-1.0.7
{ pkgs ? import <nixpkgs> {} }:

let repos = [
        "https://repo1.maven.org/maven2/"
        "https://repo.clojars.org/" ];

  in rec {
      fetchmaven = pkgs.callPackage (pkgs.fetchurl {
        url = "https://raw.githubusercontent.com/NixOS/nixpkgs/ba5e2222458a52357a3ba5873d88779d5c223269/pkgs/build-support/fetchmavenartifact/default.nix";
        sha512 = "05m7i8hbhyfz7p2f106mfbsasjf04svd9xkgc26pl3shljrk0dfacz39wiwzm6xqw7czgrsx745vciram7al621v7634nfdq3m1x88a";
      }) {};
      makePaths = {extraClasspaths ? null}:
        (pkgs.lib.concatMap
          (dep:
            builtins.map
            (path:
              if builtins.isString path then
                path
              else if builtins.hasAttr "jar" path then
                path.jar
              else if builtins.hasAttr "outPath" path then
                path.outPath
              else
                path
                )
            dep.paths)
          packages)
        ++ (if extraClasspaths != null then [ extraClasspaths ] else []);
      makeClasspaths = {extraClasspaths ? null}: builtins.concatStringsSep ":" (makePaths {inherit extraClasspaths;});
      packageSources = builtins.map (dep: dep.src) packages;
      packages = [
  rec {
    name = "transit-java/com.cognitect";
    src = fetchmaven {
      inherit repos;
      artifactId = "transit-java";
      groupId = "com.cognitect";
      sha512 = "660d4f034af67793ec53f00c661e57dd94817a3d1ab978163fe6289e06f16fe3f8431496c8e4eff1b9729cc2c47e906b6afb933605034fc2b64829c33fb47d99";
      version = "1.0.343";
      
    };
    paths = [ src ];
  }

  rec {
    name = "elemental2-core/com.google.elemental2";
    src = fetchmaven {
      inherit repos;
      artifactId = "elemental2-core";
      groupId = "com.google.elemental2";
      sha512 = "feac71c23abd3a3b02949d5844541490a9d6a6247b5707ca3791ef3cff93de09d712b1220e46a18b37b5bcfae5d93533fc59eaddeb7f4b8432b3a637f190f04d";
      version = "1.0.0-RC1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.json/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "data.json";
      groupId = "org.clojure";
      sha512 = "3a046fe64fbd10dc100f79b1d24de0d157b95a7d84661ff469b7af999eb9ceb6b3092481583c32a28fb3e43b3dc5c811787b0b0ca7cb742a093a1714fe032272";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojure/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "clojure";
      groupId = "org.clojure";
      sha512 = "f28178179483531862afae13e246386f8fda081afa523d3c4ea3a083ab607d23575d38ecb9ec0ee7f4d65cbe39a119f680e6de4669bc9cf593aa92be0c61562b";
      version = "1.10.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljsjs/thheller";
    src = fetchmaven {
      inherit repos;
      artifactId = "shadow-cljsjs";
      groupId = "thheller";
      sha512 = "0e69a94b1f62a3b4fa3f49f6c453eef2ae694f77cf3a6aab9a03f94bd0e753d090c70db861ea2846ea9d4eabd70c5d21bdb7980a99f13a2e74318f09aacd1e3f";
      version = "0.0.21";
      
    };
    paths = [ src ];
  }

  rec {
    name = "pathom/com.wsscode";
    src = fetchmaven {
      inherit repos;
      artifactId = "pathom";
      groupId = "com.wsscode";
      sha512 = "56e2125d20f6704f802830f0698e90889fcbd9a315d1835141b132303f7b3043277ded8d120037b09d4b90f7e73adf03a89e0017277a7e018cbedaee30ad909c";
      version = "2.2.31";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javax.activation-api/javax.activation";
    src = fetchmaven {
      inherit repos;
      artifactId = "javax.activation-api";
      groupId = "javax.activation";
      sha512 = "8ee0db43ae402f0079a836ef2bff5d15160e3ff9d585c3283f4cf474be4edd2fcc8714d8f032efd72cae77ec5f6d304fc24fa094d9cdba5cf72966cc964af6c9";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "icu4j/com.ibm.icu";
    src = fetchmaven {
      inherit repos;
      artifactId = "icu4j";
      groupId = "com.ibm.icu";
      sha512 = "bd8d716c1561169a74be4f932627921a186b008c964155692bede5e69491eab54109f6a40a2d14a16bdc221e27dbd5938d74743cc9e2e0b47dff933d7964b644";
      version = "66.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-codec/commons-codec";
    src = fetchmaven {
      inherit repos;
      artifactId = "commons-codec";
      groupId = "commons-codec";
      sha512 = "d9586162b257386b5871e7e9ae255a38014a9efaeef5148de5e40a3b0200364dad8516bddd554352aa2e5337bec2cc11df88c76c4fdde96a40f3421aa60650d7";
      version = "1.11";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "tools.analyzer";
      groupId = "org.clojure";
      sha512 = "e02d7baec926e0e0a7d9c71f09fee627fbde59ae7f3cbd4abcdf0533c8a87fba8c7cf4503df34bf33777063f4b6353a022552fd003fdbea9fad5752d53609bb8";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljs-test-display/com.bhauman";
    src = fetchmaven {
      inherit repos;
      artifactId = "cljs-test-display";
      groupId = "com.bhauman";
      sha512 = "d8aafc0214bb3719adbb2c957e6a7c939e0db65a0bf69c4369654f736882c3203a4eeb66670e1da18f60faa8bf97b094712472ce883a5a1a5f8dd52b8e413d96";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reagent/reagent";
    src = fetchmaven {
      inherit repos;
      artifactId = "reagent";
      groupId = "reagent";
      sha512 = "ea074140c549a8d5df554e2590bbb9d0e3522bd4f41977980afefd961ffa4bd75cfe1b7d55d51dae7596561169ab46ee5ae98f84f388ff46ce2f2d0365c2e07a";
      version = "0.9.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "error_prone_annotations/com.google.errorprone";
    src = fetchmaven {
      inherit repos;
      artifactId = "error_prone_annotations";
      groupId = "com.google.errorprone";
      sha512 = "c9521d6b31c5dbf04b77f128ee568edfb0266c0e8d199e1050b32ff54493736d73721661f139d75da24f126c2e2dd0e851c0cf6e14e7302942be08f211f3c2b5";
      version = "2.3.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.logging/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "tools.logging";
      groupId = "org.clojure";
      sha512 = "5ffdf6b5985d443a2f75460a9036c147e8aa4add1f92d8d59cb6bc25d692436cd060d884996dc2f034d3cf93771883032ea22c4e1ca1c942f6c804fb9e0ce59a";
      version = "0.4.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.specs.alpha/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.specs.alpha";
      groupId = "org.clojure";
      sha512 = "348c0ea0911bc0dcb08655e61b97ba040649b4b46c32a62aa84d0c29c245a8af5c16d44a4fa5455d6ab076f4bb5bbbe1ad3064a7befe583f13aeb9e32a169bf4";
      version = "0.2.44";
      
    };
    paths = [ src ];
  }

  rec {
    name = "eql/edn-query-language";
    src = fetchmaven {
      inherit repos;
      artifactId = "eql";
      groupId = "edn-query-language";
      sha512 = "b3ddcd9bad0b9effa8a00add3041fbbde352f36c06d5491e139181160a459d0b71ad2b4b5e5903dea5dfaad9a86f6d7014e1ade3f06843632aa9cd358f062323";
      version = "0.0.9";
      
    };
    paths = [ src ];
  }

  rec {
    name = "undertow-core/io.undertow";
    src = fetchmaven {
      inherit repos;
      artifactId = "undertow-core";
      groupId = "io.undertow";
      sha512 = "2da3cc245018eb71746be519cd07b66efc9ef1217fbf035b18935e4b920bebf1426a61877947890c6129535657c3dd5c23b134ae33799561110ea9dad706b843";
      version = "2.1.3.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "js/org.graalvm.js";
    src = fetchmaven {
      inherit repos;
      artifactId = "js";
      groupId = "org.graalvm.js";
      sha512 = "142dc0adde88e3fe1bd005aac9aa78dc0e2386f503558ce56b9096c33aebfe3f5c51aa16e1d8745494444604e7f9ad203120c18add5084e4a7e55b0f805f793b";
      version = "20.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "expound/expound";
    src = fetchmaven {
      inherit repos;
      artifactId = "expound";
      groupId = "expound";
      sha512 = "249374c59468f7171b05c014c22260f64dd282c8d1827739f9629a4d7547d289b41b90a5698b53dd460431a08fcc547b672a3942c0d84530ac6dd6a4b7fd308e";
      version = "0.8.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec.alpha/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "spec.alpha";
      groupId = "org.clojure";
      sha512 = "18c97fb2b74c0bc2ff4f6dc722a3edec539f882ee85d0addf22bbf7e6fe02605d63f40c2b8a2905868ccd6f96cfc36a65f5fb70ddac31c6ec93da228a456edbd";
      version = "0.2.176";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.cli/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "tools.cli";
      groupId = "org.clojure";
      sha512 = "7071cef2a92ad2d245c4fa5ec625f489738df2c320e8e50ceffb23d9927f006805b632e3086e9fd514ca7ff59ad0a7a2d98f3b0e5773258a71978053d0b85d6f";
      version = "1.0.194";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-fileupload/commons-fileupload";
    src = fetchmaven {
      inherit repos;
      artifactId = "commons-fileupload";
      groupId = "commons-fileupload";
      sha512 = "a8780b7dd7ab68f9e1df38e77a5207c45ff50ec53d8b1476570d069edc8f59e52fb1d0fc534d7e513ac5a01b385ba73c320794c82369a72bd6d817a3b3b21f39";
      version = "1.4";
      
    };
    paths = [ src ];
  }

  rec {
    name = "animal-sniffer-annotations/org.codehaus.mojo";
    src = fetchmaven {
      inherit repos;
      artifactId = "animal-sniffer-annotations";
      groupId = "org.codehaus.mojo";
      sha512 = "9e5e3ea9e06e0ac9463869fd0e08ed38f7042784995a7b50c9bfd7f692a53f0e1430b9e1367dc772d0d4eafe5fd2beabbcc60da5008bd792f9e7ec8436c0f136";
      version = "1.14";
      
    };
    paths = [ src ];
  }

  rec {
    name = "http-fx/day8.re-frame";
    src = fetchmaven {
      inherit repos;
      artifactId = "http-fx";
      groupId = "day8.re-frame";
      sha512 = "975419c5b86e624ee6534b0b9bcaa54951454d16a4219e0c47f5bfc769c505f57ed7b6e6c6f28416d852965ed16eac2016c230da2ff97e02b1ecb464e1fc6cc2";
      version = "0.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "regex/org.graalvm.regex";
    src = fetchmaven {
      inherit repos;
      artifactId = "regex";
      groupId = "org.graalvm.regex";
      sha512 = "3411d14d94bec33781531feecaa2c6ea765a45bbe2c2caf5e360a1125ca350a93ab932b197ad1c0ad5570475114b20bd48bd3b643fc2d0b5061d97c714fd95d1";
      version = "20.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpasyncclient/org.apache.httpcomponents";
    src = fetchmaven {
      inherit repos;
      artifactId = "httpasyncclient";
      groupId = "org.apache.httpcomponents";
      sha512 = "1dcf26866a0747ddbca6ebabf361bc8e03c433e86e427ed244504cb2be036a9e68462e65c095945fd0c8cda589836934da3b5a741c3fbdc45446d7ac8afadf46";
      version = "4.1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.analyzer.jvm/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "tools.analyzer.jvm";
      groupId = "org.clojure";
      sha512 = "cb4a6473159811f2b3e77174b3c799735b5267d3bd2d6a7e8bb08b98a21348b964ff2c1f93b5f1502c3750fe1b4279c48317e392b40d23703aec0b0eca4898f5";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "barbary-watchservice/net.incongru.watchservice";
    src = fetchmaven {
      inherit repos;
      artifactId = "barbary-watchservice";
      groupId = "net.incongru.watchservice";
      sha512 = "94df2c848b711e49f08bafb407c9a12779eff7127b12a3b645917d4c4ff987782905de24bef479c4aa5543af9b4ccae92ce3cd5312799bf69ed75d7d00a39af1";
      version = "1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-common/org.wildfly.common";
    src = fetchmaven {
      inherit repos;
      artifactId = "wildfly-common";
      groupId = "org.wildfly.common";
      sha512 = "f99f23af23a1cc45035b87ab422affdb911769ee63dc5a1c9b3e7a39ebefee07542d2388118282b20113c196e28abce8f87cafc8b0213cdc692381edce035c46";
      version = "1.5.2.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "react-dom/cljsjs";
    src = fetchmaven {
      inherit repos;
      artifactId = "react-dom";
      groupId = "cljsjs";
      sha512 = "0f7f36a859ddf3c89b02598038ff7bff63f1ac9d14c8140627399e1666d1c08683d42b18fed737f9131ef2b3bfd0406af6fd95e2dfbb320cd7ba8907a33da7d4";
      version = "16.13.0-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-cbor/com.fasterxml.jackson.dataformat";
    src = fetchmaven {
      inherit repos;
      artifactId = "jackson-dataformat-cbor";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "746a64477a422a41feb9fd05c2956f95e19f19b471003d66035e7d21c3acfe2f3443b005d6f40a25d406a18ce8db9b8019dfaf3d0fe78cf7fbe37972857a83fc";
      version = "2.8.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "json-simple/com.googlecode.json-simple";
    src = fetchmaven {
      inherit repos;
      artifactId = "json-simple";
      groupId = "com.googlecode.json-simple";
      sha512 = "f8798bfbcc8ab8001baf90ce47ec2264234dc1da2d4aa97fdcdc0990472a6b5a5a32f828e776140777d598a99d8a0c0f51c6d0767ae1a829690ab9200ae35742";
      version = "1.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-cljs/com.cognitect";
    src = fetchmaven {
      inherit repos;
      artifactId = "transit-cljs";
      groupId = "com.cognitect";
      sha512 = "d51e909c1fd83d7e04dfa7dbc0982e31be299147823c6c6d653c020663da4479150b1b5dc8ec13dc60abce4ee7b8321197a0b0d426c5dea16c4160bae4ea1c65";
      version = "0.8.264";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "google-closure-library";
      groupId = "org.clojure";
      sha512 = "4a29ae05212b508f3d4e2f5f63c542cec3fb7c0bfd0ef01718c56e0eee6798cd727b05d63af7a912bc20d7fc10e903458bce98915464e2170337151eab4ec633";
      version = "0.0-20191016-6ae1f72f";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.logic/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.logic";
      groupId = "org.clojure";
      sha512 = "873941279442ee96197edb05406099fe97e0ceb524fd9241a1981e20f158a8a0ebae0f691f2edd089cd5c5b496b9ea4090949b2358bb4dd60476f4374479dea1";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-cljs/thheller";
    src = fetchmaven {
      inherit repos;
      artifactId = "shadow-cljs";
      groupId = "thheller";
      sha512 = "b8b22ef3248ad18189071b3b66d10c930b7e2fd5a020557f9544a9339cbbcd24b06509831681e8b3561e232e9a89a84b9f1818363bde5d8dcfb5d2f828c4cb41";
      version = "2.10.18";
      
    };
    paths = [ src ];
  }

  rec {
    name = "graal-sdk/org.graalvm.sdk";
    src = fetchmaven {
      inherit repos;
      artifactId = "graal-sdk";
      groupId = "org.graalvm.sdk";
      sha512 = "ecca00e384c694c9684b2098a810de40d43fa75febbda53ab47bf369a71d25d552e20f583c7ac9f57e69478745257985408ff443846b544578453c89c22b2a19";
      version = "20.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "clojurescript/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "clojurescript";
      groupId = "org.clojure";
      sha512 = "3ec64b01fdf64af2dd1176bb7762c40442179fd69f9cd7d87243af7a8ab26b8d00fc0b48bf93e1eb0087ec1a425f87520e048faf1abaf8eec82b760e69f21468";
      version = "1.10.773";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpcore-nio/org.apache.httpcomponents";
    src = fetchmaven {
      inherit repos;
      artifactId = "httpcore-nio";
      groupId = "org.apache.httpcomponents";
      sha512 = "328b1f7315ac6bcd73258d1a3ae43d1dda935acf4fc879bf80683f67cfe32d7e9ab3ec15352237b9a047ad033729f350220c6642487e16425d90d3bdbf5ded5c";
      version = "4.4.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec-coerce/spec-coerce";
    src = fetchmaven {
      inherit repos;
      artifactId = "spec-coerce";
      groupId = "spec-coerce";
      sha512 = "76fded8a8f1d597b4dc91900b66957b4a717bf61d3c92a61bcdc107d7ad9d3384affda89a396d692a86f540e88ec5a7f37570e82ec833708e81a529d4daa6776";
      version = "1.0.0-alpha6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-io/commons-io";
    src = fetchmaven {
      inherit repos;
      artifactId = "commons-io";
      groupId = "commons-io";
      sha512 = "4de22e2a50711f756a5542474395d8619dca0a8be0407b722605005a1167f8c306bc5eef7f0b8252f5508c817c1ceb759171e4e18d4eb9697dfdd809ac39673f";
      version = "2.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-util/org.ow2.asm";
    src = fetchmaven {
      inherit repos;
      artifactId = "asm-util";
      groupId = "org.ow2.asm";
      sha512 = "f8f693c0efdedb244ec09d0fd1e32e2c3dd392c464468abbad1d730c80fb2fdac889719c57911d5eeccaa9e20ea4fbb47452fa24b6afe31b07e7bbdf70f25466";
      version = "7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsinterop-annotations/com.google.jsinterop";
    src = fetchmaven {
      inherit repos;
      artifactId = "jsinterop-annotations";
      groupId = "com.google.jsinterop";
      sha512 = "34330e368db2e5122350dcc9237711694e4ea03bbc315163ed5fd6fd8f649ddb2dbd1224b28207802603f869de61a15439924a1fef0e864abc134242d36e1ccb";
      version = "1.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "fipp/fipp";
    src = fetchmaven {
      inherit repos;
      artifactId = "fipp";
      groupId = "fipp";
      sha512 = "0088ce6bf59bd22d3e7b16bd991f4a48bd71188b758fce2327c683e962c4e9e00e09acad032774fae1c0ac435426d8daf96908b90b1c12bb060ff554c33fc758";
      version = "0.6.23";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jboss-logging/org.jboss.logging";
    src = fetchmaven {
      inherit repos;
      artifactId = "jboss-logging";
      groupId = "org.jboss.logging";
      sha512 = "c17b8882481c0cb8fbcdf7ea33d268e2173b1bfe04be71e61d5f07c3040b1c33b58781063f8ebf27325979d02255e62d1df16a633ac22f9d08adeb5c6b83a32a";
      version = "3.4.1.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "spec-inspec/com.wsscode";
    src = fetchmaven {
      inherit repos;
      artifactId = "spec-inspec";
      groupId = "com.wsscode";
      sha512 = "6ddd3a1ae290be719f8ea235d962352a7949c38fe404cf43d45e6b975635f13f53525790d77bce5543151daeadea51849499a157ea541ac0c4aa761f040c1636";
      version = "1.0.0-alpha2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-core/com.fasterxml.jackson.core";
    src = fetchmaven {
      inherit repos;
      artifactId = "jackson-core";
      groupId = "com.fasterxml.jackson.core";
      sha512 = "a1bd6c264b9ab07aad3d0f26b65757e35ff47904ab895bb7f997e3e1fd063129c177ad6f69876907b04ff8a43c6b1770a26f53a811633a29e66a5dce57194f64";
      version = "2.8.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm/org.ow2.asm";
    src = fetchmaven {
      inherit repos;
      artifactId = "asm";
      groupId = "org.ow2.asm";
      sha512 = "7eba7097109389f48fa9142bf22d225f5d3104d68013d3b8e0a6d4054a8cd0ef64614372bdcb38987d68adb6d33a3804e98ddf112ba84dbb09d448ce702dacc4";
      version = "7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cljs-ajax/cljs-ajax";
    src = fetchmaven {
      inherit repos;
      artifactId = "cljs-ajax";
      groupId = "cljs-ajax";
      sha512 = "e013ddca3f8f7b140222976190d0d505d0eced910d7cb078b44fe86e6ec007e0b9da6656c01f6a9bddd136146c3901a87ec70c6518e5c70eca170775b416d4d4";
      version = "0.8.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "react/cljsjs";
    src = fetchmaven {
      inherit repos;
      artifactId = "react";
      groupId = "cljsjs";
      sha512 = "1dfb9ce2ff27e2a7a027cd9fb72bc3e12da151ab62f0ed85bae49439c518c0d411936fcbda486eebac382a23489aecc2f02cfb55ecfb700de07cfabee890f38b";
      version = "16.13.0-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpcore/org.apache.httpcomponents";
    src = fetchmaven {
      inherit repos;
      artifactId = "httpcore";
      groupId = "org.apache.httpcomponents";
      sha512 = "10814bfb8dcce31034f8fd6822f9da29299529b900616b78d8caf846748cf2b1e093f7b99db26a8580266e3346b822b5edb347004b0d13580e6df85cb327c93c";
      version = "4.4.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-util/thheller";
    src = fetchmaven {
      inherit repos;
      artifactId = "shadow-util";
      groupId = "thheller";
      sha512 = "803a068159276f5abf6d9cfa25f5c446c4c66d2eaec78393910cb2175b63a734c7c7effaf3064789608b1cf3899c287611c2d170fd78621193acc1fbbff1d5da";
      version = "0.7.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-js/com.cognitect";
    src = fetchmaven {
      inherit repos;
      artifactId = "transit-js";
      groupId = "com.cognitect";
      sha512 = "1a376ea0f6fee3eaef6db0827bbe49b086620508f98e970400cf5b3b1ea01289ebf591dad95bbbd4c77d6e410c34528aaeec629c17726e377e76799939deb572";
      version = "0.8.861";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-core/metosin";
    src = fetchmaven {
      inherit repos;
      artifactId = "reitit-core";
      groupId = "metosin";
      sha512 = "7751c8aac09fe94d32d5577a52b78bdcd67557c89d40b4d343c4cf689af97257533a9108e81cb855364e0b9557e8ba21b675ad35d06e2b8d6646e9fcc29ac027";
      version = "0.4.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "google-closure-library-third-party/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "google-closure-library-third-party";
      groupId = "org.clojure";
      sha512 = "5d1e7fdeb403f78af53023ae30fb61246bf55a4c8c097c77f5ae9784c299c927c3d3a1b63cb890e52f2f7b0eb5b01475f23e917865cfc5241d755a5d7a9f2801";
      version = "0.0-20191016-6ae1f72f";
      
    };
    paths = [ src ];
  }

  rec {
    name = "hiccup/hiccup";
    src = fetchmaven {
      inherit repos;
      artifactId = "hiccup";
      groupId = "hiccup";
      sha512 = "034f15be46c35029f41869c912f82cb2929fbbb0524ea64bd98dcdb9cf09875b28c75e926fa5fff53942b0f9e543e85a73a2d03c3f2112eecae30fcef8b148f4";
      version = "1.0.5";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-externs/com.google.javascript";
    src = fetchmaven {
      inherit repos;
      artifactId = "closure-compiler-externs";
      groupId = "com.google.javascript";
      sha512 = "6d3fc38a964c5e26295a9715713f8d4474faded19f0c0d6ae7ed69a3493b6f1c987af101ee4fd84d9e981dfed92038fa6a85caec8c35d0fcccf9d2951428ae75";
      version = "v20200628";
      
    };
    paths = [ src ];
  }

  rec {
    name = "javassist/org.javassist";
    src = fetchmaven {
      inherit repos;
      artifactId = "javassist";
      groupId = "org.javassist";
      sha512 = "ad65ee383ed83bedecc2073118cb3780b68b18d5fb79a1b2b665ff8529df02446ad11e68f9faaf4f2e980065f5946761a59ada379312cbb22d002625abed6a4f";
      version = "3.18.1-GA";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xnio-nio/org.jboss.xnio";
    src = fetchmaven {
      inherit repos;
      artifactId = "xnio-nio";
      groupId = "org.jboss.xnio";
      sha512 = "7f2c53222caf40793b1c956aa08ff3316a86577e6a79274050bcdf700b68546397b286e3d693c1b3036fe9175f54f76816cbf6a100ae67f9e6c20b4ca028e56d";
      version = "3.8.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "commons-logging/commons-logging";
    src = fetchmaven {
      inherit repos;
      artifactId = "commons-logging";
      groupId = "commons-logging";
      sha512 = "ed00dbfabd9ae00efa26dd400983601d076fe36408b7d6520084b447e5d1fa527ce65bd6afdcb58506c3a808323d28e88f26cb99c6f5db9ff64f6525ecdfa557";
      version = "1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "guava/com.google.guava";
    src = fetchmaven {
      inherit repos;
      artifactId = "guava";
      groupId = "com.google.guava";
      sha512 = "429ceeec0350ba98e2b089b8b70ded2ec570c3a684894a7545d10592c1c7be42dacd1fad8b2cb9123aa3612575ce1b56e1bb54923443fc293f8e9adeac2762ee";
      version = "25.1-jre";
      
    };
    paths = [ src ];
  }

  rec {
    name = "truffle-api/org.graalvm.truffle";
    src = fetchmaven {
      inherit repos;
      artifactId = "truffle-api";
      groupId = "org.graalvm.truffle";
      sha512 = "abe97d8fa7fe6d6c294528d1a6e5cf7aea904d83327dc3f0a77c5e7c6140a9ba79187ed8b0a73f12025ac6b6ae73de380c4f78df5eca3060007b5c3fbc4d82b2";
      version = "20.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "devtools/binaryage";
    src = fetchmaven {
      inherit repos;
      artifactId = "devtools";
      groupId = "binaryage";
      sha512 = "d4a890e5214c4136bb66b3397c3081fd61d3f15e231358bebebbca7fdade074aa6eab34634eabaac45bb92650d071bb7f98c124b19f9f0e0b38b0ff5e2e3e4bb";
      version = "1.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "macrovich/net.cgrand";
    src = fetchmaven {
      inherit repos;
      artifactId = "macrovich";
      groupId = "net.cgrand";
      sha512 = "41dee7fc48a0300e668ff03d71a79846d3f6feef271b58a367c44ef5ee53fc7d62c5dc83b8bd136bb3a471dfa9a9b51a1727a09f1147da37cef2ae9e1edda719";
      version = "0.2.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reagent/reagent";
    src = fetchmaven {
      inherit repos;
      artifactId = "reagent";
      groupId = "reagent";
      sha512 = "0d010c29fa3319ea4660e1febaacb20e914358b40288eb1b7e1cdc405e96cfb609b87e8eafd7c41b8620651da852531c8f2a5c9fd056993ce489010da9bb21a4";
      version = "0.10.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "msgpack/org.msgpack";
    src = fetchmaven {
      inherit repos;
      artifactId = "msgpack";
      groupId = "org.msgpack";
      sha512 = "a2741bed01f9c37ba3dbe6a7ab9ce936d36d4da97c35e215250ac89ac0851fc5948d83975ea6257d5dce1d43b6b5147254ecfb4b33f9bbdc489500b3ff060449";
      version = "0.6.12";
      
    };
    paths = [ src ];
  }

  rec {
    name = "js-scriptengine/org.graalvm.js";
    src = fetchmaven {
      inherit repos;
      artifactId = "js-scriptengine";
      groupId = "org.graalvm.js";
      sha512 = "04b10bd361b01c688e92061bae0e3f585fd9f935c7352c989a63144fcb3c6c8baa3be75930fe17645fa637aad156ad63e90ef071302c0580e7b9c5f4abf8d569";
      version = "20.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jboss-threads/org.jboss.threads";
    src = fetchmaven {
      inherit repos;
      artifactId = "jboss-threads";
      groupId = "org.jboss.threads";
      sha512 = "12d2b4c6c4f732a4b9437ae6e893087981aa2d829c9bad7089cd4cb10bccd7105e136f694e43a36e5bf234ca81294117fd9f6a07795f77c0f80d8f748c8fa529";
      version = "3.1.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "j2objc-annotations/com.google.j2objc";
    src = fetchmaven {
      inherit repos;
      artifactId = "j2objc-annotations";
      groupId = "com.google.j2objc";
      sha512 = "a4a0b58ffc2d9f9b516f571bcd0ac14e4d3eec15aacd6320a4a1a12045acce8c6081e8ce922c4e882221cedb2cc266399ab468487ae9a08124d65edc07ae30f0";
      version = "1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "transit-clj/com.cognitect";
    src = fetchmaven {
      inherit repos;
      artifactId = "transit-clj";
      groupId = "com.cognitect";
      sha512 = "efe5483c188c8e6fb7327e2b312424de920b913ec9ca89580fddceb2a964de4ce75aab79d7d3671bb362b9af73a9e25a331abd4f53ce544d9b50f83a1a07adf4";
      version = "1.0.324";
      
    };
    paths = [ src ];
  }

  rec {
    name = "args4j/args4j";
    src = fetchmaven {
      inherit repos;
      artifactId = "args4j";
      groupId = "args4j";
      sha512 = "5f0651234c8f8b130fddb39fa832c6da47d3e21bc3434307554314c47e672c28d005c64e9effe85d552190cfc27966b1f005740ffd40b4e1bec2cb257d7feedb";
      version = "2.0.26";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-commons/org.ow2.asm";
    src = fetchmaven {
      inherit repos;
      artifactId = "asm-commons";
      groupId = "org.ow2.asm";
      sha512 = "2879ae5e7b796f0777b4730fb3f21b8d42cbdbf3a090acadf2ce52082f1ea030059b0067d9a3b4d2c4b4680519a8ee9b2cf1563901931645245a973b9f60b1c2";
      version = "7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "react-dom-server/cljsjs";
    src = fetchmaven {
      inherit repos;
      artifactId = "react-dom-server";
      groupId = "cljsjs";
      sha512 = "a17ada0966dca11abba401ea954c16ca1affd71bb1fe32a72ec48e69d6269bd709a964496e49e8c36d3d74cd2e83f9b4b61dbc27d83a05ad627da6aadf5393f0";
      version = "16.13.0-0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-random/crypto-random";
    src = fetchmaven {
      inherit repos;
      artifactId = "crypto-random";
      groupId = "crypto-random";
      sha512 = "0551fba1c86871b1e70fe80679d78f11bec678ccad07f7b40cc7de1e97a3ec11f7df43dd86508869765cb1a6b2b5aa5cac6d10a5d319a26df8f513ec2bfa29e8";
      version = "1.2.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "base/com.google.jsinterop";
    src = fetchmaven {
      inherit repos;
      artifactId = "base";
      groupId = "com.google.jsinterop";
      sha512 = "7a52fd9332d122b48b4c2c7dd6db5781120ee3e5cd4f8e71381fc70522d6ecb56dfcf01dfe32df21d5d7b6e7cc7dee199d0b20b5b326656c43f90acbf570155f";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-codec/ring";
    src = fetchmaven {
      inherit repos;
      artifactId = "ring-codec";
      groupId = "ring";
      sha512 = "ea95b9da61885cb433cfb4f4d8f1efb70d105df6a5ff7493e8182df5402b9f762dd66613d882d54d117a7330d58f9fa46fc4227a9bebf94a509fd25ee427a7cb";
      version = "1.1.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "shadow-client/thheller";
    src = fetchmaven {
      inherit repos;
      artifactId = "shadow-client";
      groupId = "thheller";
      sha512 = "b1f2ac82b31841d265af0939ecc0824e6ba8cc28d15b44c77f3abb305b5e88465b839915a222016c2ac8c7e2049d1daa2a3eebb9a58cdc9cf653bc56712b4ca7";
      version = "1.3.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "httpclient/org.apache.httpcomponents";
    src = fetchmaven {
      inherit repos;
      artifactId = "httpclient";
      groupId = "org.apache.httpcomponents";
      sha512 = "f8d4a960ed235770570afaf793c4596404adfa777e08bdb87ae2db92575db5e11755025fe43969f852ef505a390833e79bdd1fccd5f3fb7dee87625607b504a2";
      version = "4.5.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.rrb-vector/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.rrb-vector";
      groupId = "org.clojure";
      sha512 = "7b6546bbd0ff8c7755382a5460029f57f562529ef66fc6ca473c4ba30d897ac5ff0aec8db737da9deeb732fccdd35c9c2317c256b7703e8e5804d1098e9bf77b";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "crypto-equality/crypto-equality";
    src = fetchmaven {
      inherit repos;
      artifactId = "crypto-equality";
      groupId = "crypto-equality";
      sha512 = "54cf3bd28f633665962bf6b41f5ccbf2634d0db210a739e10a7b12f635e13c7ef532efe1d5d8c0120bb46478bbd08000b179f4c2dd52123242dab79fea97d6a6";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "checker-qual/org.checkerframework";
    src = fetchmaven {
      inherit repos;
      artifactId = "checker-qual";
      groupId = "org.checkerframework";
      sha512 = "3c38b0b9e0bde464268cff5fdb1894a048240b039093ee3abe5b32976a22737d26b355f8793f630a7f0b319fdb019a6fcd9ee1d5219676f0f10c0b0f496b61b7";
      version = "2.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "wildfly-client-config/org.wildfly.client";
    src = fetchmaven {
      inherit repos;
      artifactId = "wildfly-client-config";
      groupId = "org.wildfly.client";
      sha512 = "3f442478c57f7dfac7039f6c7ae014bb2d45cdbd690ee631a3349edbca414adfe1984d065d1439f9b1546fa15fbd032c3a6bfe008f1ad50eef74201467b9f55f";
      version = "1.0.1.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "async-error/org.clojars.akiel";
    src = fetchmaven {
      inherit repos;
      artifactId = "async-error";
      groupId = "org.clojars.akiel";
      sha512 = "4802f27d1ccd479d56a1d276c6406f64170d95db56918fd108a764c94e27fad00f90ea25525f721439d840f20f0100d5c677253fb89b4e38c3c8b485e4417d92";
      version = "0.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jna/net.java.dev.jna";
    src = fetchmaven {
      inherit repos;
      artifactId = "jna";
      groupId = "net.java.dev.jna";
      sha512 = "a380b303d5ece14b3a45dbac8d06e3f39fe5e09f3a5d08c161262c47a14326a9f5cbcdc56d6fabf6efcdb7449c4a2e43e696ec6c8c35730fb34a2993c6647948";
      version = "3.2.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "cheshire/cheshire";
    src = fetchmaven {
      inherit repos;
      artifactId = "cheshire";
      groupId = "cheshire";
      sha512 = "1fca5406bb1b2decdc0b96006a1828f02c94a06dacabb0fccb92bfb61258cdf415d2acfbef0550b56d94f24adbe90073d463afda480b233b65c000da4015d9cd";
      version = "5.7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tigris/tigris";
    src = fetchmaven {
      inherit repos;
      artifactId = "tigris";
      groupId = "tigris";
      sha512 = "5393fe3f656521a6760d289d9549ffb9e9c1a8a72b69878205d53763802afa8778f1cb8bed6899e0b9721de231a79b8b1254cc601c84f5374467f1cc4780a987";
      version = "0.1.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "tools.reader/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "tools.reader";
      groupId = "org.clojure";
      sha512 = "290a2d98b2eec08a8affc2952006f43c0459c7e5467dc454f5fb5670ea7934fa974e6be19f7e7c91dadcfed62082d0fbcc7788455b7446a2c9c5af02f7fc52b6";
      version = "1.3.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "nrepl/nrepl";
    src = fetchmaven {
      inherit repos;
      artifactId = "nrepl";
      groupId = "nrepl";
      sha512 = "14d14bb1925802223e6e70438ce24835d8c79f05816293fe9fe9cf36e2fb314d91cbdf8e786fce1afe827497f6d68dbbb937ebf52df184ba14f2d9ccb401562b";
      version = "0.7.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "re2j/com.google.re2j";
    src = fetchmaven {
      inherit repos;
      artifactId = "re2j";
      groupId = "com.google.re2j";
      sha512 = "a9bd66b95ede4d7576358b974db8059eef884d0ce59a1e065a3be1e84b97f50af7bbc6429968750f82faab1e666bbb9e51f8685e12051bb5407b3943804f04f6";
      version = "1.3";
      
    };
    paths = [ src ];
  }

  rec {
    name = "xnio-api/org.jboss.xnio";
    src = fetchmaven {
      inherit repos;
      artifactId = "xnio-api";
      groupId = "org.jboss.xnio";
      sha512 = "eab8904c5e2f6071f076e5f68fc7520fb4e9f292df2cc03be4ac7834f52994e9f539b52be7509280f4fb49a4ded185732e8a50ffd3417e39b540d508db34ac5f";
      version = "3.8.0.Final";
      
    };
    paths = [ src ];
  }

  rec {
    name = "closure-compiler-unshaded/com.google.javascript";
    src = fetchmaven {
      inherit repos;
      artifactId = "closure-compiler-unshaded";
      groupId = "com.google.javascript";
      sha512 = "bc57d9068e66b2dc4fb7803a4e9e897a44f84f2a6dcc08725a0bceeb511151cfce43541d0bcf644f32185340e81f0cc02a139671d215fea782d23214f43c6e97";
      version = "v20200628";
      
    };
    paths = [ src ];
  }

  rec {
    name = "test.check/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "test.check";
      groupId = "org.clojure";
      sha512 = "68caa189e7292da5dfde92d795ce35ff1980108a579dc11ca618bf0e480101b8ded16fc8ab816b30f364afbccbb8f02fc9194271e7f5323b8042d468164ecb64";
      version = "1.1.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "reitit-frontend/metosin";
    src = fetchmaven {
      inherit repos;
      artifactId = "reitit-frontend";
      groupId = "metosin";
      sha512 = "fda9d3aaca2277804f3f4b96f5a74d7e7ed6638986b4ea2f831089940b12706ea7ff0dbc488a90f9b1c65ec44dca3e713fef9e7b1b3dd9a45b2d1170a2e36a1d";
      version = "0.4.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-analysis/org.ow2.asm";
    src = fetchmaven {
      inherit repos;
      artifactId = "asm-analysis";
      groupId = "org.ow2.asm";
      sha512 = "d74fd51f49a8278545eaaaaf808692d69f7140fa73f4cf1eec01a21d5d2a378356a5d74fadc2f6983ee023cdf6e06851f9f37a084be547120300ac97d9cc6bba";
      version = "7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "protobuf-java/com.google.protobuf";
    src = fetchmaven {
      inherit repos;
      artifactId = "protobuf-java";
      groupId = "com.google.protobuf";
      sha512 = "8bfedb8fbc46a1f9d4408236a50d53cb71750a0680f351e26c4c238c15803ee7c180fad462e885129c60d3335f98a947b170a32704265044312b1ec5daa0003a";
      version = "3.11.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.memoize/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.memoize";
      groupId = "org.clojure";
      sha512 = "28356e2e3ea8e8378d460214839cb12a303384bc47d8c00a3e986aa5d8a1f87c3f351172d8fad993b1dc8b91b06caad7f42d27e32aadecd8c5a9b8c1a8f219b5";
      version = "0.8.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "hawk/hawk";
    src = fetchmaven {
      inherit repos;
      artifactId = "hawk";
      groupId = "hawk";
      sha512 = "617ef041b7ef98c96395fd997a0f5f5028db267c4eac367c47a306405ea1eb825f826e42be8aa4462f753d264c52496e39854e4061e9ee40712dde2f57aa9efe";
      version = "0.2.11";
      
    };
    paths = [ src ];
  }

  rec {
    name = "data.priority-map/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "data.priority-map";
      groupId = "org.clojure";
      sha512 = "450e18bddb3962aee3a110398dc3e9c25280202eb15df2f25de6c26e99982e8de5cf535fe609948d190e312a00fad3ffc0b3a78b514ef66369577a4185df0a77";
      version = "0.0.7";
      
    };
    paths = [ src ];
  }

  rec {
    name = "piggieback/cider";
    src = fetchmaven {
      inherit repos;
      artifactId = "piggieback";
      groupId = "cider";
      sha512 = "e91a19d3539daed71b79523eea2592b6dc81a5ee6a8066017b2ec9957e5b171ef2816c268afd13f2c9ff53cb670b8261d526ea083e4c1584a8948a6b9b513f9b";
      version = "0.5.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jsr305/com.google.code.findbugs";
    src = fetchmaven {
      inherit repos;
      artifactId = "jsr305";
      groupId = "com.google.code.findbugs";
      sha512 = "bb09db62919a50fa5b55906013be6ca4fc7acb2e87455fac5eaf9ede2e41ce8bbafc0e5a385a561264ea4cd71bbbd3ef5a45e02d63277a201d06a0ae1636f804";
      version = "3.0.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "re-frame/re-frame";
    src = fetchmaven {
      inherit repos;
      artifactId = "re-frame";
      groupId = "re-frame";
      sha512 = "fa9a41583deb69fb0f6fe7243ad1b64ed9d7a0d97e116ae05b9304c37376a4d276f491ccf918187c9e6d44d9624a43494752f3b78ff21195b6280963ee04fe89";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "ring-core/ring";
    src = fetchmaven {
      inherit repos;
      artifactId = "ring-core";
      groupId = "ring";
      sha512 = "e2a8d40973c8577b37c8ad1e558c3c37dee98e883d9f4e65a4d5898ed34b703b5a352afc7076bfc5bd5d7f0fbc0ec378ebcaf1a40f5eedcf49735eb4ba5109cd";
      version = "1.8.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.cache/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.cache";
      groupId = "org.clojure";
      sha512 = "827e05656e1b0294fe21f266153ad033aacf6454fe2db19d7b9dd8cd341b547d83541f5f262167a1d289c950e575e29fdd5b9e4d59a873a2d006c37a9eb6f269";
      version = "0.8.2";
      
    };
    paths = [ src ];
  }

  rec {
    name = "meta-merge/meta-merge";
    src = fetchmaven {
      inherit repos;
      artifactId = "meta-merge";
      groupId = "meta-merge";
      sha512 = "079339d69a18e88a7cf5ce37e29bf7d9b25c93011866fac3012b11444f9e3d69f4dc017a3e88ad20faa790b38e343e0b71e9e11c44028434da3f368f377e4458";
      version = "1.0.0";
      
    };
    paths = [ src ];
  }

  rec {
    name = "asm-tree/org.ow2.asm";
    src = fetchmaven {
      inherit repos;
      artifactId = "asm-tree";
      groupId = "org.ow2.asm";
      sha512 = "7c285e6de13ced1fd6110c616f9f38120d5d37da9e39be1b6fc16224595f54f645c675313f75ed819ae27e66d84e9bc378a6fb42df2f4dd2819ed745767a79ac";
      version = "7.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "core.async/org.clojure";
    src = fetchmaven {
      inherit repos;
      artifactId = "core.async";
      groupId = "org.clojure";
      sha512 = "591505d1e1b33dca6d9d641d005b271d28f620c5bb25fe8688bf186c09850ff98c5bb64dc724b44274d582e04fe2506f145ce7975d0e3545d240e423eb7b1552";
      version = "1.2.603";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jackson-dataformat-smile/com.fasterxml.jackson.dataformat";
    src = fetchmaven {
      inherit repos;
      artifactId = "jackson-dataformat-smile";
      groupId = "com.fasterxml.jackson.dataformat";
      sha512 = "ed8029cac69a1064437a6e2fcf049b4f19afe3e0187ceae176bcbf8f3d83a71a43726c82caa2e4ee5b8d8c0d40130bc761d54078cc61fed2b1180a269c8c3a61";
      version = "2.8.6";
      
    };
    paths = [ src ];
  }

  rec {
    name = "jaxb-api/javax.xml.bind";
    src = fetchmaven {
      inherit repos;
      artifactId = "jaxb-api";
      groupId = "javax.xml.bind";
      sha512 = "93a47b245ab830d664a48c9d14e86198a38809ce94f72ca66b3d68746ae1d7b902f6fef2d1ac1a92c01701549ae80a07db69bd822ffd831a95d8dbffad435790";
      version = "2.3.1";
      
    };
    paths = [ src ];
  }

  rec {
    name = "gson/com.google.code.gson";
    src = fetchmaven {
      inherit repos;
      artifactId = "gson";
      groupId = "com.google.code.gson";
      sha512 = "c3cdaf66a99e6336abc80ff23374f6b62ac95ab2ae874c9075805e91d849b18e3f620cc202b4978fc92b73d98de96089c8714b1dd096b2ae1958cfa085715f7a";
      version = "2.7";
      
    };
    paths = [ src ];
  }

  ];
  }
  